version: '3'
services:
  php: 
    container_name: php_server
    image: php:8.1-apache
    command:
      bash -c "a2enmod rewrite
      && apache2-foreground"
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80